version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
      - ./mosquitto/passwd_file:/mosquitto/passwd_file:rw
    environment:
      - TZ=${TZ:-Etc/UTC}

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - TZ=${TZ:-Etc/UTC}

  grafana:
    image: grafana/grafana:latest
    user: "0"
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./grafana:/var/lib/grafana:rw

  nodered:
    image: nodered/node-red:3.1.3
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data:rw
    environment:
      - TZ=${TZ:-Etc/UTC}