# Use the Eclipse Mosquitto base image
FROM eclipse-mosquitto:latest

# Set the timezone environment variable (if not already set)
ENV TZ=${TZ:-Etc/UTC}

# Expose ports 1883 and 9001 for Mosquitto
EXPOSE 1883 9001
